version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: node:6.10.3
    branches:
      only:
        - master
        - develop
    steps:
      - checkout
      - restore_cache:
          key: projectname-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: System information
          command: |
            echo "node $(node -v)"
            echo "npm $(npm -v)"
      - run:
          name: git config
          command: |
            git config --global user.email 'e2hjhi@gmail.com'
            git config --global user.name 'karuru6225'
      - run:
          name: merge
          command: |
            git checkout -b gh-pages
            git merge --no-ff ${CIRCLE_BRANCH}
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: reWrite ignores
          command: |
            sed --in-place=.bak -e '/^dst$/d' .gitignore
      - run:
          name: commit
          command: |
            git add -A
            git commit -m "[auto] circleci"
      - run:
          name: push
          command: git push "git@github.com:${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git" gh-pages
      - save_cache:
          key: projectname-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/workspace/node_modules

